[project]
name = "breathing-challenge"
version = "0.0.0"
requires-python = ">=3.11"

[tool.uv.workspace]
members = [
    "scoring",
    "baseline",
    "baseline-cnn-tcn",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "ruff",
]

[tool.uv]
default-groups = ['dev']

[tool.ruff]
exclude = ["**/notebooks/*.py"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "BLE", "PLW", "RUF"]
ignore = ["E501", "RUF001", "RUF002", "RUF003"]
